//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mssql_VS_FireBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int Price { get; set; }
        public int Date { get; set; }
    
        public virtual Customer Customer { get; set; }

        public Order()
        {
        }

        public Order(int id, int customer_Id, int price, int date)
        {
            Id = id;
            Customer_Id = customer_Id;
            Price = price;
            Date = date;          
        }

        public override string ToString()
        {
            return $"Id :{Id}, Customer_Id:{Customer_Id}, Price:{Price}, Date:{Date} ";
        }
    }
}
